#!/usr/bin/env python3
"""
Export one docs page per MCP tool into the asterwise-docs checkout.

The description sent to MCP clients is the compact form (see
runtime.compact_description); the full text with output and error contracts
lives in runtime.FULL_TOOL_DESCRIPTIONS and is rendered here as MDX.

    python scripts/export_tool_docs.py                # write to ../asterwise-docs
    python scripts/export_tool_docs.py --check        # exit 1 if pages differ
    python scripts/export_tool_docs.py --docs-root /path/to/asterwise-docs
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import sys
from pathlib import Path

os.environ.setdefault("ASTERWISE_API_BASE_URL", "https://api.asterwise.com")
os.environ.setdefault("JWT_SECRET", "x" * 40)

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from fastmcp import Client  # noqa: E402

from runtime import FULL_TOOL_DESCRIPTIONS, tool_doc_url  # noqa: E402
from server import mcp  # noqa: E402

SECTION_ORDER = [
    "WHAT THIS TOOL COVERS", "WORKFLOW", "INPUT CONTRACT", "OUTPUT CONTRACT",
    "RESPONSE FORMAT", "COMPUTE CLASS", "ERROR CONTRACT", "DO NOT CONFUSE WITH",
]
TITLES = {
    "WHAT THIS TOOL COVERS": "What it covers", "WORKFLOW": "Workflow",
    "INPUT CONTRACT": "Input", "OUTPUT CONTRACT": "Output contract",
    "RESPONSE FORMAT": "Response format", "COMPUTE CLASS": "Compute class",
    "ERROR CONTRACT": "Errors", "DO NOT CONFUSE WITH": "Do not confuse with",
}


def slug_for(name: str) -> str:
    return name.removeprefix("asterwise_").replace("_", "-")


def split_sections(full: str) -> tuple[str, dict[str, str]]:
    parts = re.split(r"\n\s*SECTION: ([A-Z][A-Z ]*(?:\([^)\n]*\))?)\s*\n", "\n\n" + full)
    lead = parts[0].strip()
    sections: dict[str, str] = {}
    for i in range(1, len(parts) - 1, 2):
        title = parts[i].strip()
        key = title.split(" (")[0]
        qualifier = title[len(key):].strip()
        body = parts[i + 1].strip()
        if qualifier:
            body = f"**{qualifier.strip('()')}**  \n{body}"
        sections[key] = (sections[key] + "\n\n" + body) if key in sections else body
    return lead, sections


def _mdx_escape(text: str) -> str:
    # MDX treats { } and < > as JSX; keep prose literal.
    return text.replace("{", "&#123;").replace("}", "&#125;").replace("<", "&lt;").replace(">", "&gt;")


def schema_table(schema: dict) -> str:
    props = schema.get("properties", {})
    required = set(schema.get("required", []))
    rows = ["| Parameter | Type | Required | Description |", "|---|---|---|---|"]
    for name, p in props.items():
        typ = p.get("type") or ("object" if "properties" in p else "/".join(b.get("type", "?") for b in p.get("anyOf", [])) or "?")
        if "enum" in p:
            typ = "enum: " + ", ".join(f"`{v}`" for v in p["enum"])
        desc = p.get("description", "")
        if "properties" in p:
            inner = ", ".join(f"`{k}`{'*' if k in set(p.get('required', [])) else ''}" for k in p["properties"])
            desc = (desc + " Fields: " + inner).strip()
        rows.append(f"| `{name}` | {typ} | {'yes' if name in required else 'no'} | {_mdx_escape(desc)} |")
    return "\n".join(rows)


def render_page(tool: dict, full: str) -> str:
    lead, sections = split_sections(full)
    slug = slug_for(tool["name"])
    out = [
        "---",
        f"id: {slug}",
        f"title: {json.dumps(tool['title'] or tool['name'])}",
        f"description: {json.dumps(lead.split('. ')[0][:150])}",
        "hide_table_of_contents: false",
        "---",
        "",
        "{/* AUTO-GENERATED by asterwise-mcp/scripts/export_tool_docs.py. Do not edit. */}",
        "",
        f"`{tool['name']}`",
        "",
        _mdx_escape(lead),
        "",
        "## Parameters",
        "",
        schema_table(tool["inputSchema"]),
    ]
    for key in SECTION_ORDER:
        body = sections.get(key)
        if not body:
            continue
        out += ["", f"## {TITLES[key]}", "", _mdx_escape(body).replace("\n", "  \n")]
    out += ["", "## Connect", "",
            "Remote MCP endpoint: `https://mcp.asterwise.com/mcp`. Authenticate with `Authorization: Bearer <API key>` or OAuth. See the [MCP setup guide](/guides/mcp-setup).", ""]
    return "\n".join(out)


def render_index(tools: list[dict]) -> str:
    lines = ["---", "id: index", "title: \"MCP tools\"", "slug: /mcp/tools/", "---", "",
             "{/* AUTO-GENERATED by asterwise-mcp/scripts/export_tool_docs.py. Do not edit. */}", "",
             f"The Asterwise MCP server exposes {len(tools)} read-only tools. Each page lists the parameters, the output contract and the errors a tool can return.", "",
             "| Tool | Summary |", "|---|---|"]
    for t in sorted(tools, key=lambda t: t["name"]):
        lead, _ = split_sections(FULL_TOOL_DESCRIPTIONS[t["name"]])
        lines.append(f"| [{t['name']}](./{slug_for(t['name'])}) | {_mdx_escape(lead.split('. ')[0])} |")
    return "\n".join(lines) + "\n"


async def load_tools() -> list[dict]:
    async with Client(mcp) as c:
        return [t.model_dump(mode="json") for t in await c.list_tools()]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--docs-root", type=Path, default=REPO_ROOT.parent / "asterwise-docs")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    out_dir = args.docs_root / "docs" / "mcp" / "tools"
    tools = asyncio.run(load_tools())
    pages = {out_dir / f"{slug_for(t['name'])}.mdx": render_page(t, FULL_TOOL_DESCRIPTIONS[t["name"]]) for t in tools}
    pages[out_dir / "index.mdx"] = render_index(tools)
    pages[out_dir / "_category_.json"] = json.dumps({"label": "MCP tools", "position": 90, "link": {"type": "doc", "id": "mcp/tools/index"}}, indent=2) + "\n"
    if args.check:
        drift = [str(p) for p, content in pages.items() if not p.is_file() or p.read_text() != content]
        extra = [str(p) for p in out_dir.glob("*.mdx") if p not in pages] if out_dir.is_dir() else []
        if drift or extra:
            print("DRIFT:", *drift, *extra, sep="\n  ")
            return 1
        print(f"{len(pages)} tool doc pages match.")
        return 0
    out_dir.mkdir(parents=True, exist_ok=True)
    for p, content in pages.items():
        p.write_text(content)
    for p in out_dir.glob("*.mdx"):
        if p not in pages:
            p.unlink()
    print(f"wrote {len(pages)} files to {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
