"""Horoscope, Gochar, and transit analysis."""

from __future__ import annotations

from fastmcp import Context, FastMCP

from mcp.shared.exceptions import McpError
from pydantic import ValidationError

from client import get_client, safe_segment
from errors import AsterwiseMCPError
from models import BirthData, HoroscopePeriod, ResponseFormat
from runtime import (
    STANDARD_ANNOTATIONS,
    format_tool_result,
    invalid_params,
    require_api_key,
    structured_markdown,
    tool_error,
    raise_validation_error,
    unexpected_tool_error,
)


def register(mcp: FastMCP) -> None:
    @mcp.tool(
        name="asterwise_get_horoscope",
        description="Generate a fresh horoscope reading for a Moon sign and time period.\nComputed from live planetary positions at the time of the request —\nnot pre-written static text. Covers daily themes, career, relationships,\nhealth, timing slots, remedy, and an open-loop forward indicator.\nGenerated by AI synthesis from live transit data.\n\nMoon sign accepts both Sanskrit names (Tula, Vrischika, Karka, Simha,\nKanya, Dhanu, Makara, Kumbha, Meena, Mesha, Vrishabha, Mithuna) and\nEnglish names (Libra, Scorpio, Cancer, Leo, Virgo, Sagittarius,\nCapricorn, Aquarius, Pisces, Aries, Taurus, Gemini). Both resolve\nidentically. Response always contains moon_sign in lowercase English.\n\nPeriod: daily, weekly, monthly, or yearly.\n\nOUTPUT CONTRACT (response_format=json):\ndata.content — { do[] (string array), body (string), love (string),\n  avoid[] (string array), money (string), career (string),\n  remedy (string), headline (string), narrative (string),\n  open_loop (string) }\ndata.model_used (string, AI model version)\ndata.generated_at (ISO UTC)\ndata.period_key (YYYY-MM-DD for daily; week/month/year identifier)\ndata.horizon ('daily', 'weekly', 'monthly', or 'yearly')\ndata.moon_sign (lowercase English, e.g. 'libra')\n\nERROR CONTRACT: Invalid moon_sign → 422. Invalid period → 422.\n\nThis is a sign-level reading, not a personal natal analysis.\nFor personal analysis use asterwise_get_natal_chart.",
        annotations=STANDARD_ANNOTATIONS,
    )
    async def asterwise_get_horoscope(
        ctx: Context,
        moon_sign: str,
        period: HoroscopePeriod,
        response_format: ResponseFormat
    ) -> str:
        """Moon-sign horoscope by period."""
        try:
            api_key = await require_api_key(ctx)
            path = (
                f"/v1/horoscope/{safe_segment(period.value)}/"
                f"{safe_segment(moon_sign.lower())}"
            )
            data = await get_client().get(path, api_key, timeout=10.0)
            return format_tool_result(
                data,
                response_format,
                lambda d: structured_markdown(f"Horoscope ({period.value}, {moon_sign})", d),
            )
        except McpError:
            raise
        except AsterwiseMCPError as exc:
            tool_error(str(exc))
        except ValidationError as exc:
            raise_validation_error(exc)
        except Exception as exc:
            unexpected_tool_error("asterwise_get_horoscope", exc)

    @mcp.tool(
        name="asterwise_get_gochar",
        description="Current planetary transits (Gochar) vs the natal chart — snapshot for\ntoday. Returns house position, Ashtakavarga Bindu score, Vedha status,\nand classical interpretation per planet.\n\nOUTPUT CONTRACT (response_format=json):\ndata.natal — { moon_sign, moon_sign_index, ascendant_sign,\n  ascendant_sign_index }\ndata.target_date (YYYY-MM-DD, today)\ndata.transits[] — 9 objects (Sun through Ketu):\n  planet, transit_sign, transit_sign_index, transit_degree,\n  is_retrograde, nakshatra, nakshatra_pada,\n  house_from_moon (int 1–12), house_from_lagna (int 1–12),\n  is_favorable_from_moon (bool), is_favorable_from_lagna (bool),\n  bindu_override (bool — true when AVK score overrides classical result),\n  vedha_active (bool), vedha_blocking_planet (planet name or null),\n  ashtakavarga_score (int or null — null for Rahu and Ketu, which\n  have no Ashtakavarga),\n  interpretation (string), themes[] (string array),\n  quality ('favorable' or 'unfavorable')\ndata.summary — { favorable_count, unfavorable_count,\n  vedha_blocked_count, overall_score, sade_sati_active,\n  sade_sati_phase, chandra_ashtama_active }\n\nTransit tool selection: use THIS for the current full transit picture.\nUse asterwise_get_dasha_transits for Dasha-period correlation.\nUse asterwise_get_transits for planning ahead over a date range.\nUse asterwise_check_sade_sati for Saturn-Moon transit detail.\n\nERROR CONTRACT: Same as asterwise_get_natal_chart.",
        annotations=STANDARD_ANNOTATIONS,
    )
    async def asterwise_get_gochar(
        ctx: Context,
        birth: BirthData,
        response_format: ResponseFormat
    ) -> str:
        """Gochar from natal chart."""
        try:
            api_key = await require_api_key(ctx)
            data = await get_client().post(
                "/v1/astro/gochar", api_key, birth.to_api_dict(), timeout=10.0
            )
            return format_tool_result(
                data,
                response_format,
                lambda d: structured_markdown("Gochar (transits)", d),
            )
        except McpError:
            raise
        except AsterwiseMCPError as exc:
            tool_error(str(exc))
        except ValidationError as exc:
            raise_validation_error(exc)
        except Exception as exc:
            unexpected_tool_error("asterwise_get_gochar", exc)

    @mcp.tool(
        name="asterwise_get_transits",
        description="Planetary ingress events and retrograde/direct stations over a custom\ndate range vs natal chart. Returns sign changes and stations for each\nplanet within the window. Maximum range: 24 months per call. Requests\nexceeding 24 months are rejected with 422.\n\nOUTPUT CONTRACT (response_format=json):\ndata.ingresses[] — one object per sign change:\n  planet, from_sign (int 0–11), to_sign (int 0–11), jd (float),\n  date_iso (ISO datetime string, local time), is_sankranti (bool —\n  true for Sun ingresses), retrograde_ingress (bool)\ndata.stations[] — one object per retrograde/direct station:\n  planet, station_type ('retrograde' or 'direct'), jd,\n  date_iso (ISO datetime string), longitude (float)\n\nERROR CONTRACT: Range > 24 months → 422 validation error.\nfrom_date after to_date → 422.\n\nTransit tool selection: use THIS for planning ahead. Use\nasterwise_get_gochar for current snapshot. Use\nasterwise_get_dasha_transits for Dasha correlation.",
        annotations=STANDARD_ANNOTATIONS,
    )
    async def asterwise_get_transits(
        ctx: Context,
        birth: BirthData,
        from_date: str,
        to_date: str,
        response_format: ResponseFormat
    ) -> str:
        """Date-range transits."""
        try:
            api_key = await require_api_key(ctx)
            body = {**birth.to_api_dict(), "from_date": from_date, "to_date": to_date}
            data = await get_client().post(
                "/v1/astro/transits", api_key, body, timeout=10.0
            )
            return format_tool_result(
                data,
                response_format,
                lambda d: structured_markdown(f"Transits {from_date} → {to_date}", d),
            )
        except McpError:
            raise
        except AsterwiseMCPError as exc:
            tool_error(str(exc))
        except ValidationError as exc:
            raise_validation_error(exc)
        except Exception as exc:
            unexpected_tool_error("asterwise_get_transits", exc)
